# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: peer.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'peer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npeer.proto\"*\n\x07Message\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"\x1a\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x1b\n\x08PeerInfo\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"$\n\x08PeerList\x12\x18\n\x05peers\x18\x01 \x03(\x0b\x32\t.PeerInfo\"\x07\n\x05\x45mpty2I\n\x04Peer\x12\"\n\x0bSendMessage\x12\x08.Message\x1a\t.Response\x12\x1d\n\x08GetPeers\x12\x06.Empty\x1a\t.PeerListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'peer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGE']._serialized_start=14
  _globals['_MESSAGE']._serialized_end=56
  _globals['_RESPONSE']._serialized_start=58
  _globals['_RESPONSE']._serialized_end=84
  _globals['_PEERINFO']._serialized_start=86
  _globals['_PEERINFO']._serialized_end=113
  _globals['_PEERLIST']._serialized_start=115
  _globals['_PEERLIST']._serialized_end=151
  _globals['_EMPTY']._serialized_start=153
  _globals['_EMPTY']._serialized_end=160
  _globals['_PEER']._serialized_start=162
  _globals['_PEER']._serialized_end=235
# @@protoc_insertion_point(module_scope)
